# app specific settings (deployment, statefulset, daemonset)
app:
  labels:
    app.kubernetes.io/component: "web"
  containerSpec:
  - name: "nginx"
    image:
      uri: nginx:latest
      pullPolicy: "IfNotPresent"
    env:
    - name: myenv
      value: myvalue
    readinessProbe:
      httpGet:
        path: /
        port: 80
    livenessProbe:
      httpGet:
        path: /
        port: 80
    resources:
      requests:
        memory: 50Mi
        cpu: 50m
      limits:
        memory: 500Mi
        cpu: 200m
    extraVolumes:
      mounts: []
  - name: "ubuntu"
    image:
      uri: "ubuntu"
      pullPolicy: "IfNotPresent"
    env: []
    readinessProbe: {}
    livenessProbe: {}
    extraVolumes:
      mounts: []
    resources: {}


service:
  enabled: true
  type: "ClusterIP"
  externalPort: "8080"
  targetPort: "80"
