apiVersion: apps/v1
kind: {{ .Values.app.type }}
metadata:
  name: {{ include "app.name" . }}
  {{- if .Values.namespaceOverride }}
  namespace: {{ .Values.namespaceOverride }}
  {{- end }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
  annotations:
    {{- include "app.annotations" . | nindent 4 }}
spec:
  {{- if ne .Values.app.type "DaemonSet" }}
  replicas: {{ .Values.app.replicas }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "app.labels" . | nindent 6 }}
  {{- if eq .Values.app.type "StatefulSet" }}
  serviceName: {{ include "service.name" . }}
  {{- end }}
  template:
    metadata:
      labels:
        {{- include "app.labels" . | nindent 8 }}
      annotations:
        {{- include "app.annotations" . | nindent 8 }}
    spec:
      {{- if .Values.app.nodeSelector}}
      nodeSelector:
        {{- include "app.nodeSelector" . | nindent 8}}
      {{- end }}
      {{- if .Values.app.serviceAccount }}
      serviceAccountName: {{ .Values.app.serviceAccount }}
      {{- end }}
      automountServiceAccountToken: {{ .Values.app.automountServiceAccountToken}}
      {{- if .Values.app.tolerations }}
      tolerations:
        {{ toYaml .Values.app.tolerations | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.app.gracePeriod }}
      {{- if .Values.app.pullSecrets }}
      imagePullSecrets:
      {{- range .Values.app.pullSecrets }}
      - name: {{ .name }}
      {{- end }}
      {{- end }}
      {{- if .Values.app.priorityClass }}
      priorityClassName: {{ .Values.app.priorityClass }}
      {{- end }}
      {{- if .Values.app.affinity }}
      affinity:
        {{ toYaml .Values.app.affinity | nindent 8 }}
      {{- end }}
      containers:
      {{- range .Values.app.containerSpec }}
      - name: {{ .name }}
        image: {{ .image.uri }}
        imagePullPolicy: {{ .image.pullPolicy }}
        {{- if .env }}
        env:
          {{- toYaml .env | nindent 8 }}
        {{- end }}
        {{- if .extraPorts -}}
        {{- range .extraPorts }}
        ports:
        - containerPort: {{ .containerPort }}
          name: {{ .name }}
          protocol: {{ .protocol }}
        {{- end }}
        {{- end }}
        {{- if .readinessProbe }}
        readinessProbe:
          {{- toYaml .readinessProbe | nindent 10}}
        {{- end }}
        {{- if .livenessProbe }}
        livenessProbe:
          {{- toYaml .livenessProbe | nindent 10}}
        {{- end }}
        {{- if .resources }}
        resources:
          {{- toYaml .resources | nindent 10 }}
        {{- end }}
        {{- if .extraVolumes.mounts }}
        volumeMounts:
          {{- toYaml .extraVolumes.mounts | nindent 8 }}
        {{- end }}
      {{- end -}}
      {{- if and .Values.persistence.enabled ( eq .Values.app.type "StatefulSet" ) }}
  volumeClaimTemplates:
    {{- include "statefulset.volumeClaimTemplate" . | nindent 4 }}
      {{- else -}}
      {{- if .Values.app.extraVolumes.volumes }}
      volumes:
        {{- toYaml .Values.app.extraVolumes.volumes | nindent 6 }}
      {{- end }}
      {{- end }}
